### ISSUE TITLE
Bot not responding (docker)

### ISSUE THREAD

**Issue by xXxNIKIxXx** [sleeyax/aternos-discord-bot#14]
I setup the docker container without errors. After inviting the Bot to the server. Console of bot shows the new connection. If i want to send commands from the server the commands dosen´t show. Private DM's are blocket.

**Comment by sleeyax** [comment]
The commands are registered globally, so it may take a while to register them for the very first time. Try reloading discord (CTRL + R) if they still don't show up after more than 5 minutes. Also, make sure you gave your discord bot permissions to create application commands (see screenshot below) and that your discord account/user has permissions to access commands in the text channel.

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/30344294/164816671-2ffc95da-5ac1-4040-bb27-3760ac7c5d5f.png">

**Comment by xXxNIKIxXx** [comment]
Thank you. I forgot to set the application.commands in scope. Now iths working. Thanks for the fasr support.
