### ISSUE TITLE
block commands

### ISSUE THREAD

**Issue by CodebySven** [sleeyax/aternos-discord-bot#15]
Can you block commands in discord bv. /stop
I have a public MC server on Aternos and i want to
block /stop want players do /stop and than stops the server. Is there a possible way
To block that command?

**Comment by CodebySven** [comment]
@sleeyax

**Comment by CodebySven** [comment]
And is it possible to give people premission without doing to execute commands
And that they can do /start always

**Comment by sleeyax** [comment]
See https://github.com/sleeyax/aternos-discord-bot/discussions/11#discussioncomment-2561932 it answers part of your question.

**Comment by sleeyax** [comment]
Discord now provides a [built-in way](https://discord.com/blog/slash-commands-permissions-discord-apps-bots) to manage slash command permissions in your Discord server. There's no more need for an in-house solution!
