### ISSUE TITLE
Run command

### ISSUE THREAD

**Issue by deseve** [sleeyax/aternos-discord-bot#16]
Hello if your running it on  replit what is the run command for Go language

**Comment by sleeyax** [comment]
Why would you use replit? Just use vscode, goland or a even a terminal like a sane developer...

If whatever IDE you use can't execute the `go run main.go` or `go build` commands it's broken and I do not want to support it. Feel free to create a PR if you figure it out though.

**Comment by sleeyax** [comment]
That being said if by reading the replit docs you should be able to set environment variables and then run `go run cmd/main.go`

https://docs.replit.com/programming-ide/storing-sensitive-information-environment-variables
