### ISSUE TITLE
The bot doesn't appear on the / commands. 

### ISSUE THREAD

**Issue by Aishi-teru** [sleeyax/aternos-discord-bot#18]
![image](https://user-images.githubusercontent.com/43822412/166678545-1bc17f75-95fe-4afd-b933-6a8e1dd5d409.png)

Idk but last 2 days ago it started, my members couldn't start the server cuz it's not appearing on the chat. 

Tried kicking the bot and now I can't configure it cuz it doesn't appear

**Comment by sleeyax** [comment]
That's odd although I have experienced this issue in development before. I'm not sure yet why this is happening exactly, as the commands are just registered globally at the start of the bot...

Does this issue also occur when you create a new temporary discord server and add the bot there?

**Comment by sleeyax** [comment]
Just created a new test discord server myself and the commands did show up, even after reload and on mobile as well :thinking: this is gonna be very annoying to figure out...

Have you tried the following:
- Reload discord with CTRL + R (or restart the app)
- Kick the bot, wait a  brief moment and then add it again

**Comment by Aishi-teru** [comment]
Yeah, i got it now. maybe a few bug after discord updates or something.

**Comment by sleeyax** [comment]
I recently learned discord is rolling out slash commands v2. Could be related to that. It'll be looking into improvements later.
