### ISSUE TITLE
/start issue

### ISSUE THREAD

**Issue by Ghostgalaxy5798** [sleeyax/aternos-discord-bot#19]
I followed all the steps and double checks and when i used /start this comes up:
:x: Failed to start! Reconfigure the bot with /configure and try again. See /help if the problem persists.

**Comment by Ghostgalaxy5798** [comment]
> I followed all the steps and double checks and when i used /start this comes up: ❌ Failed to start! Reconfigure the bot with /configure and try again. See /help if the problem persists.

fixed it now lol

**Comment by sleeyax** [comment]
> > I followed all the steps and double checks and when i used /start this comes up: x Failed to start! Reconfigure the bot with /configure and try again. See /help if the problem persists.
> 
> fixed it now lol

Great to hear that you figured it out yourself! Could you please share your solution though? That way other people who may stumble upon this issue in the future can benefit from it as well.

**Comment by Ghostgalaxy5798** [comment]
i just forgot to run the server manually before using the bot
