### ISSUE TITLE
[BUG] Failed to initialize worker (websocket connection timeout)

### ISSUE THREAD

**Issue by Arkapro** [sleeyax/aternos-discord-bot#28]
Im getting this message everytime i use the start command
![image](https://user-images.githubusercontent.com/86039884/167791128-09f2915c-d8b6-4b93-8eb0-b7663e8650ea.png)

**Comment by Arkapro** [comment]
> What's your Discord server ID? Then I can check the logs.
> 
> See [this article](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) if you don't know how to get that information.

**Comment by Arkapro** [comment]
789737040178315285

**Comment by Arkapro** [comment]
> closed this [2 minutes ago](#event-6587861702)

https://www.pornhub.com/categories

**Comment by Arkapro** [comment]
789737040178315285

**Comment by sleeyax** [comment]
I can see these related logs:
```
2022/05/11 06:48:38 worker 789737040178315285: Server is loading
2022/05/11 06:49:23 worker 789737040178315285: Message channel closed. Trying to reconnect 3 more time(s)...
2022/05/11 06:49:26 worker 789737040178315285: Message channel closed. Trying to reconnect 2 more time(s)...
2022/05/11 06:49:29 worker 789737040178315285: Message channel closed. Trying to reconnect 1 more time(s)...
2022/05/11 06:49:32 worker 789737040178315285: Max number of websocket connection retries reached.
2022/05/11 06:49:32 worker 789737040178315285: Background routines stopped & connections closed
```

For some reason the connection is closing, though other people seem to be able to connect just fine atm. Is anything special going on with your server? Can you start it manually over at aternos.org?

**Comment by Arkapro** [comment]
Hi, i checked my aternos.. it seems everytime i reopen aternos.. im getting logged out..and all the access i gave to people are removed...Please help

**Comment by Arkapro** [comment]
Hey listen, can u remove all data from my server in ur bot.... my server is getting offline randomly..

**Comment by sleeyax** [comment]
> Can u remove all data from my server in ur bot

You can do so yourself by kicking the bot from your server. It will delete all stored settings.

>  The bot is really good and useful.. but its making the server go offline even when no one has used the /stop command.

That's impossible. The bot doesn't send any stop commands unless you tell it to. I think some external factor is causing your server to stop and the discord bot is only letting you know about it.

**Comment by sleeyax** [comment]
Also, you didn't answer my previous question. Do you see any error or warning message when you log in and out on aternos.org? I can't help you if you don't provide enough details for me to debug the issue!

**Comment by Arkapro** [comment]
![image](https://user-images.githubusercontent.com/86039884/168003049-adb487b6-6544-45bc-bad3-8a9c010f2c4d.png)

**Comment by Arkapro** [comment]
WHAT TO DO OF THIS NOW??

**Comment by sleeyax** [comment]
Unfortunately there's nothing I can do to get your account back. When you added the bot to your server you automatically accepted this repo's TOS, which explicitly says usage is at your own risk.

I've put the bot in [maintenance mode](https://github.com/sleeyax/aternos-discord-bot/discussions/32) until it's (hopefully) safer to use again. In the meantime, the only thing you can do right now is create a new account + host the bot yourself if you still want to use it.

I'm closing this issue now because it's not related to the bot software itself and I've already given a temporary solution.
