### ISSUE TITLE
[SELF-HOSTED] 
Getting this message when start 
x Access forbidden. Please try again later.



### ISSUE THREAD

**Issue by yash8dev** [sleeyax/aternos-discord-bot#42]
**Logs**
If applicable, add logs from the bot here.
```
PASTE LOGS HERE 
```

**Screenshots**

**System information**
Please edit the required information below. Remove where not applicable.

Type: `VPS`
Provider: `replit`

Database and version: non

**Comment by sleeyax** [comment]
Unfortunately replit IPs are blocked by CloudFlare (which aternos is using).

**Comment by sleeyax** [comment]
Closing this issue because there's no solution other than not using replit to run the bot in production.
