### ISSUE TITLE
[BUG] Bot saying "Invalid credentials. Use /configure to reconfigure the bot." Even though ATERNOS_SERVER and ATERNOS_SESSION is added

### ISSUE THREAD

**Issue by DragHeru** [sleeyax/aternos-discord-bot#44]
Well I was trying to start the server from using the bot it was supposed to say it is going to start but no it says invalid credentials. I tried reconfiguring the bot by adding the ATERNOS_SERVER and ATERNOS_SESSION again multiple times but the bot keeps on saying Invalid Credentials.

![image](https://user-images.githubusercontent.com/70899053/171077235-c098dc66-5fd9-459c-a694-98559e55feda.png)

**Comment by Blackcepler** [comment]
Same For me

**Comment by sleeyax** [comment]
Bot seems to be having some connection issues. Just restarted it and seems to be working a bit better now, though there's no guarantee it will continue to.

**Comment by AUUUUUUUUUGH** [comment]
> now the issue is still there

Same for me

**Comment by sleeyax** [comment]
So are you guys still having this issue? Can't reproduce this locally so I'm still thinking this is a VPS hosting issue.

**Comment by SnowFlakeLOL** [comment]
I'm getting the same problem and i kicked the bot and added it back in but it still does it?

**Comment by SnowFlakeLOL** [comment]
does anyone know what to do??

**Comment by sleeyax** [comment]
Hmm I'm noticing this in the logs, likely related to the security challenge:
```
2022/08/11 21:24:47 worker xxx: unexpected end of JSON input
```

**Comment by sleeyax** [comment]
Read https://github.com/sleeyax/aternos-discord-bot/discussions/61.
