### ISSUE TITLE
[BUG] I were starting server and this happened 

### ISSUE THREAD

**Issue by AUUUUUUUUUGH** [sleeyax/aternos-discord-bot#47]
**Describe the bug**
The bag says ":x: Failed to start! Reconfigure the bot with /configure and try again. See /help if the problem persists." when i restarted the server bug stayed and I don't know what to do.

Idk what happened but I hope you will read it and help me I am creating a server for myself fr so I hope the answer will be soon as possible.

<img width="823" alt="Screenshot 2022-06-09 at 20 41 16" src="https://user-images.githubusercontent.com/107212717/172920916-76dcd193-d949-42c8-963a-aa8963bbdc9b.png">

(just to let you know if that could help, I am macOS user)

**Comment by sleeyax** [comment]
I'm seeing a lot of `Aternos failed to start the server.` in the logs. That can mean one of the following:
- It's a temporary issue on their end
- You misconfigured the bot
- They changed something security related, breaking the bot in the process.

**Comment by AUUUUUUUUUGH** [comment]
Maybe the 3 one because I tried it on many laptops and it still did not work even on them, also I used different VPNs and browsers.

**Comment by sleeyax** [comment]
Actually, I can see in the log it only happens with one server (probably your discord server). So it's most likely nr 1 or 2. Did you start the server manually and accept EULA before using the bot? Read `/help`, it's stated in there.

**Comment by AUUUUUUUUUGH** [comment]
Yes i accept it and tried to restart server again and there is still this problem :(

**Comment by CodebySven** [comment]
@AUUUUUUUUUGH  Try this:

1. Kick the bot
2. Invite the bot
3. Run your Aternos Server
4. config the bot
5. try again!

**Comment by sleeyax** [comment]
Closing because I believe the actual problem OP is facing now is  #44 Reopen if I'm wrong.
