### ISSUE TITLE
[SELF-HOSTED] 

### ISSUE THREAD

**Issue by falconishere** [sleeyax/aternos-discord-bot#50]
**Describe the issue**
A clear and concise description of what the issue or question is.

**Logs**
If applicable, add logs from the bot here.
```
PASTE LOGS HERE 
```

**Screenshots**

**System information**
Please edit the required information below. Remove where not applicable.

Bot version: `version x.x.x`
Type: `VPS`
Provider: `linode`
Operating system: `Linux 5.17.5-arch1-1 x86_64 GNU/Linux`
Database and version: `MongoDB v14.4.14`
My aternos account got suspensed because of your bot , so how would i remove the access of your bot to my minecraft server

**Comment by sleeyax** [comment]
You opened an issue labeled as 'self hosted' and didn't fill in the required information. It's unlikely you actually got banned by actually self hosting the  bot though.

I'm therefore assuming you used the demo, which is indeed,as stated  EVERYWHERE, at risk to get your account banned. 

You can delete all associated data by simply removing the bot from your discord server.
