### ISSUE TITLE
[SELF-HOSTED] not responding to commands

### ISSUE THREAD

**Issue by ModcoLocko** [sleeyax/aternos-discord-bot#51]
Bot does not respond to commands.

I have given the discord bot full permissions, and have added it to my server (when adding, the console logs of the bot being on also showed this) however the bot does not respond to any commands. I am trying in the general channel of my server. Commands also don't show up when putting in /

**Comment by ModcoLocko** [comment]
I have now tested the same bot in discord developer panel, but used a old program I wrote in python instead of the aternos bot. And it works.

**Comment by sleeyax** [comment]
Reload discord. Commands can take a while to register.

**Comment by ModcoLocko** [comment]
I have tried that and it does not work. However when I add the public bot it registers commands instantly

**Comment by sleeyax** [comment]
It's the exact same binary program though. Are you sure the bot is online and has proper permissions to access the channel? Maybe it does register the commands but you just can't see them.

**Comment by ModcoLocko** [comment]
I created a new basic discord server, and generated the link to give the bot for admin privileges, started the bot, it registers the joining of the server, but does not register any commands, or respond to them.

**Comment by sleeyax** [comment]
You probably forgot to set the correct permission in the oauth url when you added the bot to the server.

See https://github.com/sleeyax/aternos-discord-bot/issues/14#issuecomment-1107033646
