### ISSUE TITLE
[SELF-HOSTED] 

### ISSUE THREAD

**Issue by Giochi-Sp** [sleeyax/aternos-discord-bot#53]
Hello! Can you please tell me what's the problem here? i typed all require but it says 
"Missing environment variables!"
Thx

![image](https://user-images.githubusercontent.com/82823716/178267414-314e72d7-9040-4432-b2b5-df0da61e309b.png)

Bot version: Last version
Type: WIndows 10
Operating system: Windows
Database and version: No added (is not required as how you said)

**Comment by sleeyax** [comment]
On the second line you typed set twice.

**Comment by Giochi-Sp** [comment]
Oh sorry forgive me XD

**Comment by sleeyax** [comment]
Np, lmk if it works. Then we can close this issue.
