### ISSUE TITLE
[BUG] failed to start

### ISSUE THREAD

**Issue by Executer1** [sleeyax/aternos-discord-bot#58]
It Just Kept Poping Up the Same thing Over And Over Again
![💬╏mod-chat - Discord 11-08-2022 21_22_38](https://user-images.githubusercontent.com/111074778/184176186-deb1571c-daeb-480b-b7e9-622a84122d53.png)

Please Help Me

**Comment by sleeyax** [comment]
Is this a brand new MC server? If so, you must start the MC server at least once from aternos before using the discord bot.

**Comment by Moatesem123** [comment]
> 

I made it many times and it doesn't work

**Comment by sleeyax** [comment]
Looking at the logs aternos returns an unexpected status code when starting the server:
```
2022/08/12 19:38:45 worker 461923725080788994: Starting server
Unexpected HTTP status code 418 (418 I'm a teapot)
Response body:
 <nil>
```

It works fine locally though, which leads me to believe aternos is ban-hammering the public bot instance. This is a cat and mouse game so the only real way to 'fix' this is to host the bot yourself ¯\_(ツ)_/¯

**Comment by sleeyax** [comment]
Read https://github.com/sleeyax/aternos-discord-bot/discussions/61.
