### ISSUE TITLE
[BUG] the application did not respond

### ISSUE THREAD

**Issue by Clowner1884** [sleeyax/aternos-discord-bot#60]
**Describe the bug**
For some reason whenever I use /configure with the valid credentials it just says "the application did not respond." But I'm not sure if it is an aternos issue or discord issue because I used /ping and it was able to respond.

**Expected behavior**
I expected the bot to configure correctly so I could start my aternos server through discord.

**To Reproduce**
(MIGHT NOT WORK FOR EVERYONE)
1. I did /configure
2. I filled in the credentials
3. it responded with "the application did not respond."

**Screenshots**
![image](https://user-images.githubusercontent.com/101290814/184985654-be4c7085-2dbb-48da-9162-45ef8a0764b9.png)

**Other information**
Add any other information or context about the problem here.

**Comment by Clowner1884** [comment]
UPDATE: everything except /ping is saying "The application did not respond"

**Comment by sleeyax** [comment]
Sounds like a discord or VPS issue. The public bot is in ~ 1000 servers so some downtime is to be expected. Host it yourself to avoid issues like this.

**Comment by sleeyax** [comment]
Read https://github.com/sleeyax/aternos-discord-bot/discussions/61. Create a new issue if you're experiencing the same issue with a self-hosted bot.
