### ISSUE TITLE
[BUG] Access forbidden help

### ISSUE THREAD

**Issue by DYNOXY** [sleeyax/aternos-discord-bot#63]
It is showing access forbidden [ErrorPic](https://cdn.discordapp.com/attachments/1009125353949769781/1012645799374626836/Screenshot_2022-08-26-14-21-07-692_com.Discord.jpg)

**Comment by backslashin** [comment]
i have this same issue

**Comment by sleeyax** [comment]
Please provide more information such as which hosting platform/method you are using.

**Comment by sleeyax** [comment]
Closing due to missing information.
