### ISSUE TITLE
[BUG] Invalid Credentials /configure to configure

### ISSUE THREAD

**Issue by KaibatsuEvol** [sleeyax/aternos-discord-bot#67]
**Describe the bug**
When I use /start it says Invalid Credentials and told me to configure it, when I finish configuring it and do /start again it says the same thing
**Expected behavior**
To start the server

**To Reproduce**
1. Give aternos session and server cookie to thing 
2. Start thing
3. do /start

**Screenshots**

**Other information**
Add any other information or context about the problem here.

**Comment by KaibatsuEvol** [comment]
By the way I did read the other bug reports and I couldn't find a solution stated anywhere, this is self-hosted on my old computer

**Comment by sleeyax** [comment]
Log in to aternos in a web browser and start the server at least once to accept the EULA. Then try again.

**Comment by KaibatsuEvol** [comment]
alright i'll try that

**Comment by TimPGamer** [comment]
i have the same probleme and it does not work
