### ISSUE TITLE
Docker connect denied 

### ISSUE THREAD

**Issue by Alexander975** [sleeyax/aternos-discord-bot#68]
it was working yesterday but today when i tried docker logs aternos-discord-bot it gave me 
![image](https://user-images.githubusercontent.com/92925599/199021740-2b3c3b70-f40e-4bc5-a96a-9066228d63b2.png)
pls help

**Comment by Alexander975** [comment]
i am using linux deepin version 20

**Comment by sleeyax** [comment]
This isn't an issue with this project. Learn the [basics of docker](https://docs.docker.com/engine/install/linux-postinstall/); you need to add your user to the sudoers group or use the docker commands with sudo.
