### ISSUE TITLE
Access is forbidden Bug Windows 10 RDP & 3,5 GB RAM

### ISSUE THREAD

**Issue by rtn31x** [sleeyax/aternos-discord-bot#69]
Hello, I have now installed go language on the Windows 10 Platform on the virtual machine and your video ( https://www.youtube.com/watch?v=bS_NhM6dJpw&t=198s ) I applied everything, added it to my server, but Access is forbidden. Please try again later. I'm getting the error I checked all the information is correct can you solve it

**Comment by sleeyax** [comment]
Assuming this is fixed by now. Reopen if the issue persists.
