### ISSUE TITLE
Missing environment variables!

### ISSUE THREAD

**Issue by rttyy** [sleeyax/aternos-discord-bot#76]
running on replit,
I wrote in the shell :
"$ set DISCORD_TOKEN=<value>
$ set ATERNOS_SESSION=<value>
$ set ATERNOS_SERVER=<value>"

**Comment by sleeyax** [comment]
Set isn't the right command to set environment variables on linux. Just write VAR=value instead. Note that these are temporary values, you should store them in your shell config file to make it permanent. See this article (or google it yourself): https://phoenixnap.com/kb/linux-set-environment-variable

________________________________
From: rttyy ***@***.***>
Sent: Saturday, January 21, 2023, 3:22 PM
To: sleeyax/aternos-discord-bot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sleeyax/aternos-discord-bot] Missing environment variables! (Issue #76)


running on replit,
I wrote in the shell :
"$ set DISCORD_TOKEN=
$ set ATERNOS_SESSION=
$ set ATERNOS_SERVER="

**Comment by rttyy** [comment]
Thanks !!

**Comment by rttyy** [comment]
![image](https://user-images.githubusercontent.com/79284347/213874980-561994e5-fc11-427b-adcc-617a41afdd55.png)
![image](https://user-images.githubusercontent.com/79284347/213874991-869fa6d9-dd52-4a47-8756-cdcf276b7a7e.png)
 the problem persists

**Comment by sleeyax** [comment]
Lookup "replit environment variables" in replit docs or Google, there's probably a specific way to set them.
________________________________

**Comment by rttyy** [comment]
![image](https://user-images.githubusercontent.com/79284347/213876280-b1222f30-a584-45dc-9904-0580f2c1fabf.png)
new error

**Comment by rttyy** [comment]
could you help me ?

**Comment by sleeyax** [comment]
Did you change anything in the source code? Go.mod shouldn't contain the things the compiler warns about. Also, make sure to use the version of go that is listed there.

________________________________

**Comment by rttyy** [comment]
I'm going to reset the project and I'll tell you

**Comment by sleeyax** [comment]
Hey I just ran it myself on replit, you need to configure the environment variables in the [secrets](https://docs.replit.com/programming-ide/storing-sensitive-information-environment-variables) section.

**Comment by rttyy** [comment]
hi ! thank you very much, I would just like to be sure, what is the command to run the bot (with the source code)

**Comment by sleeyax** [comment]
The command to use is in the readme. It's the one you used. I think you should be able to hit 'run' on replit somewhere directly though.

**Comment by rttyy** [comment]
Thank you 😊! It works perfectly on remplit and on my Linux computer
