### ISSUE TITLE
Not pulling mongo from docker hub

### ISSUE THREAD

**Issue by Benzopyrene** [sleeyax/aternos-discord-bot#77]
**Describe the bug**
As shown in [the video](https://www.youtube.com/watch?v=-20pZ7_nHTA&ab_channel=Sleeyax), it should say `Unable to find image 'mongo:5' locally`, and then `5: Pulling from library/mongo` but all it responds with is: `docker: no matching manifest for linux/arm/v7 in the manifest list entries.`

**Other information**
I am trying to host it on a RaspberryPi if this makes a difference. I suspect it's something to do with the fact it uses arm64 architecture right?

**Comment by sleeyax** [comment]
Yes, please use a search engine and look up how to install mongo on raspberry pi. This is not an issue related to this project.
