### ISSUE TITLE
/start showing " :x: Failed to initialize worker (websocket connection timeout)! See /help or try again later. " 

### ISSUE THREAD

**Issue by Alexander975** [sleeyax/aternos-discord-bot#78]
Ok so , sometime ago i finished configuring the bot and i started it and it worked , i played with my friends for 2 hours and then i stopped the server using /stop now when i am using /start again its giving the following output :x: Failed to initialize worker (websocket connection timeout)! See /help or try again later.
![image](https://user-images.githubusercontent.com/92925599/221908598-612a6d69-b06f-4fa9-93c4-f91d1092c742.png)

**Comment by sir-zan** [comment]
This is what is shows in the logs 

![image](https://user-images.githubusercontent.com/126597536/221929414-a9df1e04-6fe9-404e-aba5-90c63d802c95.png)

**Comment by minklepop** [comment]
hi, is it working now? also btw how did u set up the proxy for your device? could u link me a docker tutorial by any chance?
