### ISSUE TITLE
[SELF-HOSTED] Starting Problem with Linux

### ISSUE THREAD

**Issue by TimPGamer** [sleeyax/aternos-discord-bot#80]
**Describe the issue**
I have a Raspberry Pi with Kali Linux on it and it wont even start. Is Kali Linux not supported or have I done something wrong?
Please Help me If you can.

**System information**

Bot version: `version 2.3.0`
Operating system: `Kali Linux arm64 on a Raspberry Pi3`

**Comment by sleeyax** [comment]
Kali is based on debian so I don't see why it wouldn't work. Please provide more info about what you tried and what the output logs are.

**Comment by TimPGamer** [comment]
Thanks for responding so fast

I had set all the envoirement variables and then I tried to start the file, but It just said, that the file didnt exist or something and no i have not made a mistake with the name i checked it 3 times. Have you made a video or something on how to do it?

**Comment by sleeyax** [comment]
Please post output logs 'the file didn't exist or something' doesn't tell me much. My best guess is you're probably trying to enter the command in the wrong directory.

**Comment by sleeyax** [comment]
Check this video, it's the same on kali

https://youtu.be/-20pZ7_nHTA

**Comment by TimPGamer** [comment]
I had to reinstall the whole operating system, because I have just kind of destroyed it... , but that is no necesarry info....
So this time I just came to the step where i have to config the docker and now there is the problem and the Command line says:
"sudo: docker: command not found" 
(The command i used is the same as in the video: sudo docker run -d --name ...).
I know in the beginning of this issue it was because of starting (i tried in wrong dir) and I am really sorry, that its a whole different issue now, but please help me one more time. I am really sorry, if for wasting your time.

**Comment by sleeyax** [comment]
Sounds like you didn't install docker. Literally read the docs for your OS: https://www.kali.org/docs/containers/installing-docker-on-kali/

Your issue doesn't have much to do with this project.

**Comment by sleeyax** [comment]
Alternatively, skip the docker step and download the latest binary release [here](https://github.com/sleeyax/aternos-discord-bot/releases). Extract the archive and copy the contents to your pi. Then start it like `ATERNOS_SESSION="your session here" ATERNOS_SERVER="your server here" ./aternos-discord-bot`.

**Comment by TimPGamer** [comment]
you have forgotten to mention the Bot Token, but it i okay, because It is running now. I thank you a lot for helping me with my problems. I hope i didnt waste your Time.
